### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by XzAeRo** [AleChelli/smart-citizen-node-api#1]
Hey @AleChelli !

Will you keep supporting future development in this repo?
I'm interested in submitting some pull requests. Part of the code is broken, and other parts need more improvements.

Thanks for your work so far!

**Comment by AleChelli** [comment]
Hey @XzAeRo !

I have created the repo, and I have no time for future development in the meanwhile. I'm very happy if you want to submitting pull requests and so on. 

Waiting for yours improvements
BR

**Comment by XzAeRo** [comment]
Perfect.
Expect some pull requests in the next days.
